version: '3'
services:
  mysql:
    container_name: laravel_mysql
    image: mysql:5.7.22
    environment:
      TZ: "Europe/Moscow"
      MYSQL_DATABASE: 'laravel'
      MYSQL_ROOT_PASSWORD: 'toor'
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysql", "-uroot", "-ptoor"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - mysql_volume:/var/lib/mysql:cached
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf:cached
    networks:
      - default

  redis:
    container_name: laravel_redis
    image: bitnami/redis:latest
    networks:
      - default
    environment:
      TZ: "Europe/Moscow"
      REDIS_PASSWORD: toor
    expose:
      - "6379"
    ports:
      - "6378:6379"
    volumes:
      - redis_volume:/bitnami:cached

  phpmyadmin:
    container_name: laravel_phpmyadmin
    image: phpmyadmin/phpmyadmin
    ports:
      - 8080:80
    networks:
      - default
    environment:
      TZ: "Europe/Moscow"
      PMA_HOST: mysql
    links:
      - mysql
    expose:
      - 80

  nginx:
    container_name: laravel_nginx
    image: nginx:stable-alpine
    ports:
      - 80:80
    volumes:
      - ./laravel:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/site.conf:/etc/nginx/conf.d/site.conf
      - ./logs:/logs:cached
      - sock_volume:/var/run
    links:
      - php
    depends_on:
      - php
    networks:
      - default

  php:
    container_name: laravel_php
    image: bitnami/php-fpm
    environment:
      TZ: "Europe/Moscow"
    working_dir: /var/www/html
    volumes:
      - ./laravel:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini:cached
      - ./php/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      - ./php/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf:cached
      - sock_volume:/var/run
    #command: bash -c "bash init.sh && php-fpm"
    restart: on-failure
    depends_on:
      - mysql
      - redis
    networks:
      - default

volumes:
  mysql_volume: {}
  redis_volume: {}
  sock_volume: {}

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.32.0.0/16